### ISSUE TITLE
关于项目微服务框架选择的问题

### ISSUE THREAD

**Issue by intyouss** [toomanysource/atreus-old#1]
项目需基于微服务与rpc架构，由于项目的体积问题，只需寻找一个轻便简洁的微服务框架

**Comment by mo3et** [comment]
I recommend [Kratos](https://go-kratos.dev/).  It's better documented and better community help.

**Comment by Dyamidsteve** [comment]
I'll raise my hand for kratos

**Comment by mo3et** [comment]
Finally chose Kratos.
