### ISSUE TITLE
关于项目使用三方库选择

### ISSUE THREAD

**Issue by intyouss** [toomanysource/atreus-old#3]
对于mysql,redis等中间件连接，我们需要使用语言支持三方库来使用。Go语言的三方库都可在其官网搜索并按支持度排序。我推荐使用官方推荐的每个第一位

**Comment by alilestera** [comment]
Now we are not sure what component have to use. After we discuss about it, this issue might available.

**Comment by alilestera** [comment]
go-redis, gorm, kafka-go

**Comment by mo3et** [comment]
- [go-redis](https://github.com/redis/go-redis)
- [gorm](https://github.com/go-gorm/gorm.io)
- [kafka-go](https://github.com/segmentio/kafka-go)
