### ISSUE TITLE
关于项目架构的讨论

### ISSUE THREAD

**Issue by Dyamidsteve** [toomanysource/atreus-old#4]
并不是用了微服务框架就是微服务项目了，还能弄项目部署，包括网关等，且还需做隔离，如果全都在单机上，那这微服务就没有意义了

**Comment by intyouss** [comment]
需要租服务器吗

**Comment by intyouss** [comment]
如果真的按照正规部署可不止一台服务器

**Comment by mo3et** [comment]
上docker么

**Comment by intyouss** [comment]
必然要用docker，我们目前的环境没办法真的实现完整版的微服务，可以开多个容器可以的

**Comment by Dyamidsteve** [comment]
我还是觉得至少需要两台机器来承载多个微服务，数据库和网关可以放一起

**Comment by intyouss** [comment]
可以看看有没有云服务器的免费额度，我阿里云还有一个月

**Comment by Youzi-nya** [comment]
我还有一台腾讯云的服务器，能帮得上大家的忙就好。我可能不大会操作，到时候希望各位大佬教教

**Comment by Li1Mo0N** [comment]
我有一个阿里云的服务器，可以供大家使用
