### ISSUE TITLE
2023-07-25 会议讨论

### ISSUE THREAD

**Issue by alilestera** [toomanysource/atreus-old#6]
主题：2023-07-25 会议讨论
时间：7月25日 (今天) 20:30 - 21:30 (GMT+8)
会议 ID：418 429 861
会议链接：https://vc.feishu.cn/j/418429861

手机拨号一键入会
+862122504720,,418429861（中国大陆）
4008208888,,418429861（中国大陆）

根据所在地拨打号码
+86 21 2250 4720（中国大陆）
400 820 8888（中国大陆）
+852 2245 3212（中国香港）
+44 20 3433 3816（英国）

议题：
- #1 
- #3 
- #4 
- #5 

欢迎感兴趣的小伙伴参加，有想交流讨论的议题可以直接留言。

**Comment by mo3et** [comment]
# Summary
## Tech Stack
- Kratos
- Gorm
- go-redis
- Kafka
- gRPC
- TBC.

## Tasks
Parse structure first. Create corresponding tasks and assign someone.

## Ref structure
![23fbeecf-691c-4e22-a939-59a4d3a93581](https://github.com/toomanysource/Atreus/assets/34803812/9c93926d-5369-4d8a-aaa0-2a15cc160cdf)


## TODO
- [ ] layout structure
- [ ] functional structure
- [ ] database structure.  [structure ref](https://bytedance.feishu.cn/docx/BhEgdmoI3ozdBJxly71cd30vnRc)
- [ ] Dockfiles & CICD(Recommend Github Action) files

### Other
Docs structure ref: [HammerCloth/tiktok](https://github.com/HammerCloth/tiktok)
Src details ref: [Toktik-Team/toktik](https://github.com/Toktik-Team/toktik)
[Kratos Project layout](https://go-kratos.dev/blog/go-project-layout/)
[gRPC quickstart](https://grpc.io/docs/languages/go/quickstart/)
[Example API docs](https://apifox.com/apidoc/shared-09d88f32-0b6c-4157-9d07-a36d32d7a75c/api-50707523)

**Comment by alilestera** [comment]
can keep for a while
